force-app/main/default/objects/Training_Report__c/Training_Report__c.object-meta.xml
<CustomObject>
    <label>Training Report</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Training Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Report__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Training_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingReportTest.cls
/*
* https://github.com/mmilidoni/sfdc-training-report-employee-sharing
* 
* MIT License 
* Copyright (c) 2022 Michele Milidoni
* 
*/

@IsTest
public class TrainingReportTest {
    
    @IsTest
    public static void testAll() {
        List<User> lstUser = new List<User>();
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        for(Integer i=0; i < 10; i++) {
            User u = new User(Alias = 'stdm' + i, Email='standarduser' + i + '@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='michelemstandarduser' + i + '@testorg.com');
            lstUser.add(u);
        }

        insert lstUser;

        List<Training_Report__c> trs = new List<Training_Report__c>();
        for(Integer i=0; i < 200; i++) {
            trs.add(new Training_Report__c(
                OwnerId=lstUser.get(0).Id,
                Employee__c=lstUser.get(1).Id
            ));
        }

        Test.startTest();
        insert trs;
        for(Training_Report__c tr : trs) {
            tr.Employee__c = lstUser.get(2).Id;
        }
        update trs;

        DataBase.executeBatch(new TrainingReportEmployeeShareRecalcBatch()); 

        Test.stopTest();


    }
}