force-app/main/default/objects/Training_Report__c/Training_Report__c.object-meta.xml
<CustomObject>
    <label>Training Report</label>
    <nameField>
        <displayFormat>TR-{0000}</displayFormat>
        <label>Training Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Reports</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Report__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Training_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TrainingReportEmployeeShareRecalcBatch.cls
/*
* https://github.com/mmilidoni/sfdc-training-report-employee-sharing
* 
* MIT License 
* Copyright (c) 2022 Michele Milidoni
* 
*/

public class TrainingReportEmployeeShareRecalcBatch implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, Employee__c
        FROM Training_Report__c]);
    }

    public void execute(Database.BatchableContext BC, List<Training_Report__c> scope) {
        TrainingReports trs = new TrainingReports(scope);
        trs.unshareWithEmployee();
        trs.shareWithEmployee();
    }

    public void finish(Database.BatchableContext BC){}
}